### ISSUE TITLE
Add picotts has provider

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/speaker#1]
Hi,
It's possible to add picotts to provider ? With it we can make TTS without internet.

Thank in advance

**Comment by duncan3dc** [comment]
An offline provider with non-php dependencies could introduce a lot of issues, but I'll give it some thought

**Comment by zoic21** [comment]
I open my issue on duncan3dc/speaker github, it's not ok ?

**Comment by duncan3dc** [comment]
Sorry, my fault, you did the right thing

**Comment by duncan3dc** [comment]
Just to let you know I've done [some work](https://github.com/duncan3dc/speaker/commit/a9ae7deb16bab1e8dd946913f1b381ce99e0fc75) on this and it should be possible to put in the next release

**Comment by zoic21** [comment]
Hi,
Great, with that we can make TTS without cloud.

Thank a lot

**Comment by duncan3dc** [comment]
@zoic21 Sorry for the delay, I forgot all about this :disappointed: 
It's available in [0.7.0](http://duncan3dc.github.io/speaker/providers/picotts/), let me know if there's any issues
