### ISSUE TITLE
I haven't Jumped Yet!!

### ISSUE THREAD

**Issue by talibbash** [duncan3dc/speaker#11]
Duncan,
I have a friend who has become physically impaired particularly where speech is concerned. I am by far no programmer... at best an ok kludge.  I have a project/toy that i have been working at that I think could benefit my friend... the project is mypersonaldictionary.com  what I'd love to do is add a button that will cause the users device to speak the text in the box... 

I hope this post is received well as i suspect that many of my concerns likely have been dealt fatal blows.

**Comment by duncan3dc** [comment]
Hi @talibbash, what is the issue you would like help with?

**Comment by talibbash** [comment]
How to get/Where to start/What is next? ... I have a web toy that delivers text to and from MySQL; I want to create an option for turning/making text to speech a device dependent choice... to say whats in the box. essentially form collected date with simple management and user notification by email... i want to add speech and sms
I found speaker joined github and clicked on PHP....  stuck... alice is through the looking glass.

**Comment by duncan3dc** [comment]
Ok no problem, I presume you aren't using `composer` yet, I'd recommend [getting started](https://getcomposer.org/doc/00-intro.md) there, as that is how this library is installed.

Once you've got composer running, you can [install](http://duncan3dc.github.io/speaker/installation/) this library, and then write something like this:
```php
require_once __DIR__ . "vendor/autoload.php";

use duncan3dc\Speaker\TextToSpeech;
use duncan3dc\Speaker\Providers\GoogleProvider;

$provider = new GoogleProvider;

$tts = new TextToSpeech("Hello World", $provider);
$tts->save("/tmp/hello.mp3");
```

You've need to save it somewhere you can access from your existing codebase (`/tmp/hello.mp3` should be fine if you're on linux). Then you should be able to use something like the [`<audio>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) tag to play the audio to your website users.

Good luck!
