### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by ghost** [duncan3dc/speaker#12]
tried the .php example, i thought it may be that google doesn't offer a TTS api any longer?

haven't tried the others.  
getting a 500 'page isn't working'

```
<?php 
error_reporting(E_ALL);
require_once "vendor/autoload.php";

use duncan3dc\Speaker\TextToSpeech;
use duncan3dc\Speaker\Providers\GoogleProvider;

$provider = new GoogleProvider("en");

$tts = new TextToSpeech("Hello World", $provider);
$tts->save("/tmp/hello.mp3");
?>
```

**Comment by duncan3dc** [comment]
Hi @barrycox, I have seen people reporting that the free google service is no longer available.
Please try one of the other providers available, if you're aware of a TTS service not available please let me know and I'll create a provider for it
