### ISSUE TITLE
 didn't know what i should do exactly .. 

### ISSUE THREAD

**Issue by samaal** [duncan3dc/speaker#13]
I'm developing a website that teaches the Italian language,, I need tts to help the student  recognizing the pronunciation of the words 

so please could you help me,, I have tried the google API but it doesn't work anymore 

start with me step by step, please .. thank you

**Comment by duncan3dc** [comment]
Hi @samaal,

The [documentation](http://duncan3dc.github.io/speaker/usage/) provides step by step instructions on getting started.

Then there is a list of the available providers on the left hand side. If the Google API is not working anymore, please try one of the other ones
