### ISSUE TITLE
symfony/process v2.3.0 conflicts with symfony/console

### ISSUE THREAD

**Issue by Vutik** [duncan3dc/speaker#15]
C:\xampp\htdocs\october>composer require duncan3dc/speaker
Using version ^1.1 for duncan3dc/speaker
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for duncan3dc/speaker ^1.1 -> satisfiable by duncan3dc/speaker[1.1.0].
    - Conclusion: remove symfony/console v3.4.11
    - Conclusion: don't install symfony/console v3.4.11
    - duncan3dc/speaker 1.1.0 requires symfony/process ^2.3 -> satisfiable by symfony/process[v2.8.49].
    - symfony/process v2.8.49 conflicts with symfony/console[v3.4.11].
    - Installation request for symfony/console (locked at v3.4.11) -> satisfiable by symfony/console[v3.4.11].

Installation failed, reverting ./composer.json to its original content.

**Comment by duncan3dc** [comment]
Hi Denis, I've just released version [1.2.0](https://github.com/duncan3dc/speaker/releases/tag/1.2.0) with support for Symfony 3, so you should be able to install that version alongside your current dependencies
