### ISSUE TITLE
Symfony 4.x support

### ISSUE THREAD

**Issue by heartofalion** [duncan3dc/speaker#16]
Is Symfony 4.x support for this package currently being worked on?

**Comment by duncan3dc** [comment]
Symfony 4.0 dropped the `ProcessBuilder` which makes it impractical to use here.
I'm just looking at removing this dependency now (as I presume you just want to be able to install this library in a Symfony 4.x project)

**Comment by duncan3dc** [comment]
I've just released [1.3.0](https://github.com/duncan3dc/speaker/releases/tag/1.3.0) which can be installed alongside Symfony 4.x

**Comment by heartofalion** [comment]
Thank you so much. It's very much appreciated.
