### ISSUE TITLE
Call to undefined method GuzzleHttp\Utils::chooseHandler()

### ISSUE THREAD

**Issue by MohakAoki** [duncan3dc/speaker#22]
as you can see on the Title, when an error occurred on use line.

**Comment by duncan3dc** [comment]
Do you have some code to reproduce the error?

**Comment by MohakAoki** [comment]
i have a vendor and auto load from befor. my code doesn't throw any error. i changed your {vendor} folder name to {TTS} and on the line
require_once __DIR__ . /TTS/autoload.php
it throws error. this is full error:

`PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 /TTS/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 /TTS/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#2 /vendor/longman/telegram-bot/src/Request.php(282): GuzzleHttp\Client->__construct(Array)
#3 /vendor/longman/telegram-bot/src/Telegram.php(202): Longman\TelegramBot\Request::initialize(Object(Longman\Tele /vendor/guzzlehttp/guzzle/src/functions.php on line 61`

I guess its because i have 2 autoload.php and i don't know how to merge it.

**Comment by duncan3dc** [comment]
I would replace your other autoload with composer autoloading (link below) as you should only really have one, then all your dependencies and your own classes will be loaded correctly.
https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by MohakAoki** [comment]
> I would replace your other autoload with composer autoloading (link below) as you should only really have one, then all your dependencies and your own classes will be loaded correctly. https://getcomposer.org/doc/01-basic-usage.md#autoloading

I'm not very familiar with php and composer. I'm using php for my telegram bot. so if i go as the link said, my problem will be solve?
thx a lot.

**Comment by duncan3dc** [comment]
Good luck! :slightly_smiling_face:
