### ISSUE TITLE
php 8.2 Support

### ISSUE THREAD

**Issue by dipesh79** [duncan3dc/speaker#24]
I was trying to install this on Laravel project of version 11.9 and php version 8.2 but i could not install it because of this package dependency error.

Could you please add support for php 8.2 or above.

Thank you.

**Comment by duncan3dc** [comment]
Hi @Dipesh79 are you able to share the command you ran and the output you got? Along with your `composer.json` this should enable me to recreate and fix your issue

**Comment by duncan3dc** [comment]
I _think_ this was an issue with a transitive dependency, which has now been resolved so you should be able to install alongside Laravel 11 now. If not, please let me know the details above and I'll investigate further, thanks

**Comment by dipesh79** [comment]
@duncan3dc Thank you the issue has been resolved.
