### ISSUE TITLE
Better way to do this

### ISSUE THREAD

**Issue by 0vulns** [duncan3dc/speaker#3]
> I noticed almost of providers needs API Key or had limited use , I suggest to build one or update with [Responsive Voice](https://responsivevoice.org) , it's free and support more than 40 language :)

**Comment by duncan3dc** [comment]
Thanks, but it looks like that would require a browser engine to use. I'll take a deeper look soon and see if it's feasible to create a provider for it though.

**Comment by 0vulns** [comment]
This may would help you :
https://code.responsivevoice.org/getvoice.php?t=The%20Internet%20is%20a%20series%20of%20tubes!&tl=en-GB&sv=g1&vn=rjs&pitch=0.5&rate=0.5&vol=1
https://code.responsivevoice.org/getvoice.php?t={TEXT}&tl={LANG}

**Comment by duncan3dc** [comment]
Just for info @xc0d3rz, we now support [Picotts](http://duncan3dc.github.io/speaker/providers/picotts/) which doesn't require an API key or have limited use.

I will still consider Responsive Voice for a future provider
