### ISSUE TITLE
error exception: Will not follow more than 5 redirects

### ISSUE THREAD

**Issue by gabrielschuck** [duncan3dc/speaker#6]
I'm getting this message when trying to speak a text with any of voxygen's voices. The error is the same on both a local and a remote server. I'm even using an
application and today I discovered that problem. Until then it was working normal.
I went to the voxygen website and tested it there and it looks normal too.
What's going on?

**Comment by duncan3dc** [comment]
Hi @gabrielschuck, it looks like the free web service for Voxygen is no longer working.

@zoic21 Do you know where you got the original URL from? Should we be using http://ws.voxygen.fr/documentation.html instead?

**Comment by duncan3dc** [comment]
It looks like Voxygen is now a paid only service, if somebody wants to provide credentials I can update the provider to work with the authorised service, otherwise I'll remove the provider in the next release
