### ISSUE TITLE
Google tts error 503 

### ISSUE THREAD

**Issue by naruto2302** [duncan3dc/speaker#8]
I get the error message for 503 service Unavailable. I have try some python library and it call success. Please help :(
`( ! ) GuzzleHttp\Exception\ServerException: Server error: `GET http://translate.google.com/translate_tts?q=hello+world&tl=en&client=duncan3dc-speaker` resulted in a `503 Service Unavailable` response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> <html> <head><meta http-equiv="content-type" content="te (truncated...) in /Applications/XAMPP/xamppfiles/htdocs/tangthuvien/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111`

**Comment by duncan3dc** [comment]
Is that a consistent error you're getting? I've just tried it and it seems to work, I also hit your URL (http://translate.google.com/translate_tts?q=hello+world&tl=en&client=duncan3dc-speaker) in the browser with success too. Does the device you're trying this on have an internet connection? Can you access other resources?

**Comment by naruto2302** [comment]
I tried couple of times, all same error with 503 response.
I also tried this library calling to Google TTS and it succeeded https://github.com/pndurette/gTTS
When I hit (http://translate.google.com/translate_tts?q=hello+world&tl=en&client=duncan3dc-speaker) Google said that
`Our systems have detected unusual traffic from your computer network. Please try your request again later.` Maybe problem from my Mac. I will try another Computer for test and fake IP too

**Comment by duncan3dc** [comment]
Yes that explains it, Google is blocking requests from your current IP address unfortunately.
It looks like that other library is using a reverse engineered authentication token, that's not something I'm interested in supporting.

However if you pay for Google's service I'd be happy to add support for using a legal token, just open a new issue/pr for the feature, thanks
